name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
     runs-on: ubuntu-latest
     steps:
        - run: echo "The Job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "This job is now running on a ${{ runner.os }} server hosted by Gitmub!."
        - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - uses: actions/checkout@v2
        - run: echo "The workflow is now ready to test your code on the rumer."
        - run: echo "The ${{ github.repository }} repository has been cloned to the rumner."
        - run: |
            ls ${{ github.workspace }} 
        - run: echo "This job's status is ${{ job.status }}."
